# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'harbor.islands.cloud/development/cmsmvc:latest'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'harbor.crt'
    - script: |
        echo Installing $(caCertificate.secureFilePath) to the docker trusted CA directory...
        sudo mkdir /etc/docker/certs.d
        sudo mkdir /etc/docker/certs.d/harbor.islands.cloud
        sudo cp $(caCertificate.secureFilePath) /etc/docker/certs.d/harbor.islands.cloud/ca.crt
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        tags: |
          $(Build.BuildId)
          latest
        command: 'push'
