# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'harbor.islands.cloud/development/cmsmvc:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/island-cms'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/island-cms'
        command: 'push'