# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'harbor.islands.cloud/development/cmsmvc:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DownloadSecureFile@1
      inputs:
        secureFile: 'harbor.crt'
        socketTimeout: '300'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        command: 'push'