# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 'harbor.islands.cloud/development/cmsmvc:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'harbor.crt'

    - script: |
        echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...
        sudo mkdir /usr/share/ca-certificates/extra
        sudo cp $(caCertificate.secureFilePath) /usr/share/ca-certificates/extra/
        sudo cp $(caCertificate.secureFilePath) /etc/docker/certs.d/harbor.islands.cloud/ca.crt
        sudo update-ca-certificates
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'harbor-islands'
        repository: 'development/cmsmvc'
        command: 'push'
    - script: |
        echo Installing $(caCertificate.secureFilePath) to the trusted CA directory...
        sudo chown root:root $(caCertificate.secureFilePath)
        sudo chmod a+r $(caCertificate.secureFilePath)
        sudo ln -s -t /etc/ssl/certs/ $(caCertificate.secureFilePath)