on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: tanzumeaks.azurecr.io
        username: ${{ secrets.acr_tanzumeaks_username }}
        password: ${{ secrets.acr_tanzumeaks_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t tanzumeaks.azurecr.io/tanzume:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push tanzumeaks.azurecr.io/tanzume:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_tanzume_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep island-cms | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace island-cms`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: island-cms
        container-registry-url: tanzumeaks.azurecr.io
        container-registry-username: ${{ secrets.acr_tanzumeaks_username }}
        container-registry-password: ${{ secrets.acr_tanzumeaks_password }}
        secret-name: tanzumedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: island-cms
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          tanzumeaks.azurecr.io/tanzume:${{ github.sha }}
        imagepullsecrets: |
          tanzumedockerauth
